version: '3.7'

services:
  frontend:
    build:
      context: ./frontend  # Directory del Dockerfile del frontend
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend  # Directory del Dockerfile del backend
    ports:
      - 8080:8080
    depends_on:
      - mongodb
        
    environment:
      spring.data.mongodb.database: todolistdb
      spring.data.mongodb.host: mongodb
      spring.data.mongodb.port: 27017
    

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
